version: "3.5"
services:
  ca-sign-tool:
    build: .
    entrypoint: ['bash']
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ./cert
        target: /cert-volume
